"""Offline contracts for source coverage, candidate survival and evidence gates."""
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import enhanced_detection as ed
import detect_vulns as dv
import decide
import go_ast_analysis


class EnhancedTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.binary = ed.build_analyzer()

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name)

    def write(self, name, content):
        p = self.root / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)

    def index(self):
        return json.loads(subprocess.check_output([self.binary, '--source-index', '--dir', str(self.root)], text=True))

    def ctx(self):
        return ed.Context(self.root, self.index())

    def sample(self):
        self.write('a.go', 'package p\nfunc Hidden(x string) {\n opaque(x)\n}\n')
        ctx = self.ctx()
        fid = next(k for k, f in ctx.functions.items() if f['name'] == 'Hidden')
        raw = {'function_id': fid, 'category': 'other_security', 'title': 'Unknown API',
               'hypothesis': 'tainted input reaches opaque', 'trigger': 'untrusted x', 'impact': 'security effect',
               'input_path': 'unresolved entry', 'references': [ctx.reference('a.go', 3, 3)], 'questions': []}
        return ctx, raw, ed.semantic_candidate(ctx, raw, 'u', 0)

    def test_optional_full_run_raw_call_log_redacts_credentials(self):
        response = type('Response', (), {
            'status_code': 200,
            'text': '{"echo":"test-secret"}',
            'json': lambda self: {'model': 'model', 'usage': {}, 'choices': [
                {'finish_reason': 'stop', 'message': {'content': '{}'}}]},
        })()
        with tempfile.TemporaryDirectory() as output:
            with patch.dict(os.environ, {'GOFORRET_LLM_RAW_DIR': output}):
                with patch.object(dv.requests, 'post', return_value=response):
                    result, error = dv.call_llm({'LLM_BASE_URL': 'https://example.invalid',
                        'LLM_API_KEY': 'test-secret', 'LLM_MODEL': 'model',
                        'LLM_PROVIDER': 'deepseek'}, 'system', 'source')
            self.assertEqual((result, error), ({}, None))
            files = list(Path(output).glob('*.json'))
            self.assertEqual(len(files), 1)
            self.assertNotIn('test-secret', files[0].read_text())
            record = json.loads(files[0].read_text())
            self.assertEqual(record['request']['messages'][1]['content'], 'source')
            self.assertEqual(record['request']['response_format'], {'type': 'json_object'})
            self.assertEqual(record['http_status'], 200)

    def test_ast_index_covers_closures_declarations_and_malformed_files(self):
        self.write('a.go', 'package p\nvar S = "}"\nfunc F[T any](x T) { f := func(){ println("{") }; f() }\n')
        self.write('nested/b.go', 'package q\nfunc Broken(\n')
        self.write('a_test.go', 'package p\n')
        self.write('vendor/v.go', 'package v\n')
        self.write('gen.go', '// Code generated by test. DO NOT EDIT.\npackage p\n')
        self.write('outside.txt', 'secret')
        (self.root / 'link.go').symlink_to(self.root / 'outside.txt')
        idx = self.index()
        self.assertEqual({f['path'] for f in idx['files']}, {'a.go', 'nested/b.go'})
        self.assertTrue(any(s['kind'] == 'closure' for s in idx['files'][0]['spans']))
        self.assertTrue(next(f for f in idx['files'] if f['path'] == 'nested/b.go')['error'])
        self.assertEqual(len(idx['excluded']), 4)

    def test_units_cover_every_line_and_long_functions(self):
        self.write('a.go', 'package p\nfunc F(){\n' + ' println("x")\n' * 550 + '}\n')
        ctx = self.ctx()
        covered = set()
        for _, r in ctx.units():
            self.assertLessEqual(r['end_line'] - r['start_line'] + 1, ed.MAX_LINES)
            covered.update(range(r['start_line'], r['end_line'] + 1))
        self.assertEqual(covered, set(range(1, 554)))

    def test_context_rejects_escape_and_validates_exact_location(self):
        ctx, raw, _ = self.sample()
        with self.assertRaises(ValueError):
            ctx.tool({'tool': 'read_lines', 'file': '../private.go', 'start_line': 1, 'end_line': 1})
        self.assertTrue(ctx.validate_refs(raw['references']))
        raw['references'][0]['snippet'] = 'opaque(y)'
        self.assertFalse(ctx.validate_refs(raw['references']))
        with self.assertRaises(ValueError):
            ctx.tool({'tool': 'shell', 'function_id': raw['function_id']})

    def test_source_reference_accepts_only_leading_indentation_difference(self):
        self.write('a.go', 'package p\nfunc F(){\n\tif true {\n\t\tprintln("ok")\n\t}\n}\n')
        ctx = self.ctx()
        ref = ctx.reference('a.go', 3, 4)
        quoted = dict(ref, snippet='if true {\nprintln("ok")')
        self.assertTrue(ctx.validate_refs([quoted]))
        self.assertEqual(ctx.canonical_refs([quoted])[0]['snippet'], ref['snippet'])
        line_only = {'file': 'a.go', 'start_line': 3, 'end_line': 4}
        self.assertEqual(ctx.canonical_refs([line_only])[0]['snippet'], ref['snippet'])
        quoted['snippet'] = 'if false {\nprintln("ok")'
        self.assertFalse(ctx.validate_refs([quoted]))

    def test_valid_operation_candidate_survives_bad_secondary_quote(self):
        ctx, raw, _ = self.sample()
        raw['references'].append({'file': 'a.go', 'start_line': 2, 'end_line': 2,
                                  'snippet': 'func Hidden(x string)'})
        candidate = ed.semantic_candidate(ctx, raw, 'unit', 0)
        self.assertEqual(len(candidate['evidence']), 1)
        self.assertEqual(candidate['span']['sink']['line'], 3)
        self.assertEqual(candidate['reference_warnings'][0]['index'], 1)
        self.assertIn('secondary citation', candidate['questions'][-1])
        raw['references'][0]['snippet'] = 'opaque(y)'
        with self.assertRaisesRegex(ValueError, 'primary source reference'):
            ed.semantic_candidate(ctx, raw, 'unit', 0)

    def test_candidate_rebinds_unique_cited_function_with_warning(self):
        ctx, raw, _ = self.sample()
        self.write('b.go', 'package p\nfunc Other() { dangerous() }\n')
        ctx = self.ctx()
        raw['references'] = [{'file': 'b.go', 'start_line': 2, 'end_line': 2}]
        candidate = ed.semantic_candidate(ctx, raw, 'unit', 0)
        self.assertEqual(candidate['function'], 'b.go:Other')
        self.assertEqual(candidate['reference_warnings'][0]['reason'], 'function_id_rebound_to_cited_operation')
        self.write('b.go', 'package p\nfunc Other() {\n _ = func() { dangerous() }\n}\n')
        ctx = self.ctx()
        raw['references'] = [{'file': 'b.go', 'start_line': 3, 'end_line': 3}]
        with self.assertRaisesRegex(ValueError, 'outside candidate function'):
            ed.semantic_candidate(ctx, raw, 'unit', 0)

    def test_bind_extractions_by_id_and_reject_invalid_batches(self):
        def row(k):
            return dict(function_id=k, purpose=k, semantic_inputs=[], semantic_sinks=[], observed_checks=[])
        rows, errors = ed.bind_extractions([row('b'), row('a')], ['a', 'b'])
        self.assertEqual(rows['a']['purpose'], 'a')
        self.assertFalse(errors)
        legacy = row('a')
        legacy['function'] = legacy.pop('function_id')
        rows, errors = ed.bind_extractions([legacy], ['a'])
        self.assertEqual(rows['a']['function_id'], 'a')
        self.assertFalse(errors)
        for data in ([row('a'), row('a')], [row('z')]):
            self.assertEqual(ed.bind_extractions(data, ['a', 'b'])[0], {})
        self.assertEqual(ed.bind_extractions([dict(legacy, function='other')], ['a'])[0], {})
        rows, errors = ed.bind_extractions([row('b')], ['a', 'b'])
        self.assertEqual(errors, [{'function_id': 'a', 'reason': 'missing_id'}])

    def test_verdict_needs_source_backed_claims(self):
        ctx, raw, candidate = self.sample()
        def answer(status, kinds, unresolved=None):
            return {'action': 'finish', 'candidate_id': candidate['finding_id'], 'status': status,
                    'reason': 'evidence', 'unresolved': unresolved or [],
                    'claims': [{'kind': k, 'statement': 'claim', 'references': raw['references']} for k in kinds]}
        for status, kinds, expected in [('supported', ['input'], 'unknown'),
                ('supported', ['input', 'operation', 'impact'], 'supported'),
                ('refuted', ['protection'], 'unknown'),
                ('refuted', ['operation', 'protection'], 'refuted'),
                ('refuted', [], 'unknown')]:
            response = answer(status, kinds)
            out = ed.verify(ctx, lambda *a: (response, None), candidate, lambda: False)
            self.assertEqual(out['validation_status'], expected)
            self.assertEqual(out['runtime_validation'], 'not_run')
        response = answer('supported', ['input', 'operation', 'impact'], ['entry unresolved'])
        self.assertEqual(ed.verify(ctx, lambda *a: (response, None), candidate, lambda: False)['validation_status'], 'unknown')
        response = answer('refuted', ['operation', 'protection'])
        response['claims'][0]['references'] = [ctx.reference('a.go', 2, 2)]
        self.assertEqual(ed.verify(ctx, lambda *a: (response, None), candidate, lambda: False)['validation_status'], 'unknown')
        response['claims'][0]['references'] = [{'file': 'a.go', 'start_line': 99, 'end_line': 99, 'snippet': 'fake'}]
        self.assertEqual(ed.verify(ctx, lambda *a: (response, None), candidate, lambda: False)['validation_status'], 'unknown')

    def test_queries_and_budget_failures_remain_unknown(self):
        ctx, raw, candidate = self.sample()
        def ask(*args):
            return {'action': 'query', 'requests': [{'tool': 'read_function', 'function_id': raw['function_id']}]}, None
        out = ed.verify(ctx, ask, candidate, lambda: False)
        self.assertEqual(out['validation_status'], 'unknown')
        self.assertEqual(out['validation_reason'], 'investigation_budget_exhausted')
        self.assertEqual(len(out['verification_trace']), 6)
        self.assertEqual(ed.verify(ctx, ask, candidate, lambda: True)['validation_reason'], 'interrupted')
        budget = ed.ModelCallBudget(1)
        response, trace, error = ed.model_loop(ctx, ask, ed.VERIFY, {}, lambda: False, budget=budget)
        self.assertIsNone(response)
        self.assertEqual(error, 'model_call_budget_exhausted')
        self.assertEqual(len(trace), 1)
        self.assertEqual(budget.used, 1)

    def test_run_budget_keeps_unchecked_work_visible(self):
        ctx, _, candidate = self.sample()
        seen = []
        def ask(prompt, payload):
            seen.append(prompt)
            p = json.loads(payload)
            return {'action': 'finish', 'unit_id': p['unit_id'], 'candidates': []}, None
        out = ed.run(self.root, self.index(), {}, [candidate], {}, ask, max_model_calls=1)
        self.assertEqual(len(seen), 1)
        self.assertEqual(out['status'], 'partial')
        self.assertEqual(out['limits']['model_calls_used'], 1)
        self.assertEqual(out['limits']['max_model_calls'], 1)
        self.assertTrue(any(t['status'] == 'pending' and t['reason'] == 'model_call_budget_exhausted'
                            for t in out['tasks']))
        self.assertEqual(out['candidates'][0]['validation_status'], 'unknown')
        self.assertEqual(out['candidates'][0]['validation_reason'], 'model_call_budget_exhausted')

    def test_bounded_run_verifies_discovery_before_next_unit(self):
        self.write('first.go', 'package p\nfunc First(x string) { opaque(x) }\n')
        self.write('second.go', 'package p\nfunc Second() {}\n')
        ctx = self.ctx()
        first_id = next(fid for fid, f in ctx.functions.items() if f['name'] == 'First')
        units = [(uid, ref) for uid, ref in ctx.units() if ref['start_line'] == 2]
        self.assertEqual(len(units), 2)
        ctx.units = lambda: iter(units)
        candidate = {'function_id': first_id, 'category': 'other_security',
                     'title': 'Opaque operation', 'hypothesis': 'input reaches opaque',
                     'trigger': 'external x', 'impact': 'unknown security effect',
                     'input_path': 'x', 'references': [ctx.reference('first.go', 2, 2)],
                     'questions': []}
        calls = []
        def ask(prompt, payload):
            data = json.loads(payload)
            if prompt == ed.DISCOVER:
                calls.append(('discover', data['source']['file']))
                found = [candidate] if data['source']['file'] == 'first.go' else []
                return {'action': 'finish', 'unit_id': data['unit_id'], 'candidates': found}, None
            calls.append(('verify', data['candidate_id']))
            return {'action': 'finish', 'candidate_id': data['candidate_id'],
                    'status': 'unknown', 'reason': 'entry unresolved',
                    'unresolved': ['entry'], 'claims': []}, None
        out = ed.run(self.root, self.index(), {}, [], {}, ask,
                     context=ctx, max_model_calls=2)
        self.assertEqual([step for step, _ in calls], ['discover', 'verify'])
        self.assertEqual(out['candidates'][0]['validation_reason'], 'entry unresolved')
        self.assertEqual(out['limits']['discovery_calls_used'], 1)
        self.assertEqual(out['limits']['verification_calls_used'], 1)
        self.assertEqual(out['tasks'][1]['reason'], 'model_call_budget_exhausted')
        self.assertEqual(out['status'], 'partial')

    def test_bounded_run_verifies_new_discovery_before_structural_hypothesis(self):
        ctx, raw, structural = self.sample()
        structural['rule_id'] = 'R2'
        structural['input_path'] = 'structural-origin'
        selected = [(uid, ref) for uid, ref in ctx.units()
                    if ref['start_line'] <= 3 <= ref['end_line']]
        self.assertEqual(len(selected), 1)
        ctx.units = lambda: iter(selected)
        verified = []
        def ask(prompt, payload):
            p = json.loads(payload)
            if prompt == ed.DISCOVER:
                return {'action': 'finish', 'unit_id': p['unit_id'], 'candidates': [raw]}, None
            verified.append(p['candidate']['rule_id'])
            return {'action': 'finish', 'candidate_id': p['candidate_id'], 'status': 'unknown',
                    'reason': 'precondition unresolved', 'unresolved': ['precondition'], 'claims': []}, None
        out = ed.run(self.root, self.index(), {}, [structural], {}, ask,
                     context=ctx, max_model_calls=2)
        self.assertEqual(verified, ['SEMANTIC'])
        self.assertEqual(out['candidates'][0]['rule_id'], 'SEMANTIC')
        self.assertEqual(out['candidates'][1]['validation_reason'], 'model_call_budget_exhausted')

    def test_bounded_rounds_reach_distinct_investigation_groups(self):
        self.write('a.go', 'package p\nfunc F(x string) {\n opaque(x)\n other(x)\n}\n')
        ctx = self.ctx()
        fid = next(k for k, f in ctx.functions.items() if f['name'] == 'F')
        selected = [(uid, ref) for uid, ref in ctx.units() if ref['start_line'] == 2]
        ctx.units = lambda: iter(selected)
        def raw(title, line):
            return {'function_id': fid, 'category': 'other_security', 'title': title,
                    'hypothesis': title, 'trigger': 'external x', 'impact': 'effect',
                    'input_path': 'x', 'references': [ctx.reference('a.go', line, line)],
                    'questions': []}
        proposed = [raw('first claim', 3), raw('second claim', 3), raw('third claim', 4)]
        ids = [ed.semantic_candidate(ctx, row, selected[0][0], n)['finding_id']
               for n, row in enumerate(proposed)]
        calls = []
        def ask(prompt, payload):
            data = json.loads(payload)
            if prompt == ed.DISCOVER:
                calls.append('discover')
                return {'action': 'finish', 'unit_id': data['unit_id'], 'candidates': proposed}, None
            calls.append(data['candidate_id'])
            return {'action': 'query', 'requests': [
                {'tool': 'read_function', 'function_id': fid}]}, None
        out = ed.run(self.root, self.index(), {}, [], {}, ask,
                     context=ctx, max_model_calls=3)
        self.assertEqual(calls, ['discover', ids[0], ids[2]])
        self.assertEqual(len(out['investigation_groups']), 2)
        self.assertEqual({x['finding_id'] for x in out['raw_candidates']}, set(ids))
        self.assertEqual(out['candidates'][1]['validation_status'], 'unknown')
        self.assertNotEqual(out['candidates'][1]['validation_reason'], 'investigation_budget_exhausted')

    def test_one_immediate_investigation_round_per_source_unit(self):
        self.write('a.go', 'package p\nfunc A(x string) { opaque(x); other(x) }\n')
        self.write('b.go', 'package p\nfunc B() {}\n')
        ctx = self.ctx()
        fid = next(k for k, f in ctx.functions.items() if f['name'] == 'A')
        units = [(uid, ref) for uid, ref in ctx.units() if ref['start_line'] == 2]
        ctx.units = lambda: iter(units)
        source = ctx.reference('a.go', 2, 2)
        candidates = [{'function_id': fid, 'category': cat, 'title': cat,
                       'hypothesis': cat, 'trigger': 'external x', 'impact': 'effect',
                       'input_path': 'x', 'references': [source], 'questions': []}
                      for cat in ('path_validation', 'resource_limit')]
        calls = []
        def ask(prompt, payload):
            data = json.loads(payload)
            if prompt == ed.DISCOVER:
                calls.append(('discover', data['source']['file']))
                rows = candidates if data['source']['file'] == 'a.go' else []
                return {'action': 'finish', 'unit_id': data['unit_id'], 'candidates': rows}, None
            calls.append(('verify', data['candidate_id']))
            return {'action': 'query', 'requests': [
                {'tool': 'read_function', 'function_id': fid}]}, None
        out = ed.run(self.root, self.index(), {}, [], {}, ask,
                     context=ctx, max_model_calls=3)
        self.assertEqual([x[0] for x in calls], ['discover', 'verify', 'discover'])
        self.assertEqual(sum(x['status'] == 'completed' for x in out['tasks']), 2)

    def test_semantic_discovery_without_ast_sinks_or_entries(self):
        ctx, raw, _ = self.sample()
        def ask(prompt, payload):
            p = json.loads(payload)
            if prompt == ed.DISCOVER:
                return {'action': 'finish', 'unit_id': p['unit_id'], 'candidates': [raw] if p['source']['start_line'] == 2 else []}, None
            return {'action': 'finish', 'candidate_id': p['candidate_id'], 'status': 'unknown',
                    'reason': 'entry unresolved', 'unresolved': ['entry'], 'claims': []}, None
        out = ed.run(self.root, self.index(), {}, [], {}, ask)
        self.assertEqual(len(out['findings']), 1)
        self.assertEqual(out['findings'][0]['rule_id'], 'SEMANTIC')
        self.assertEqual(out['findings'][0]['validation_status'], 'unknown')
        self.assertEqual(out['status'], 'complete')

    def test_rejected_success_response_is_exposed_as_review_candidate(self):
        self.write('dns.go', '''package p
type Response struct { Code int; Answers []string }
func block(name string) *Response {
 return &Response{Code: 0, Answers: []string{name}}
}
''')
        ctx = self.ctx()
        fid = next(k for k, f in ctx.functions.items() if f['name'] == 'block')
        raw = {'function_id': fid, 'category': 'other_security',
               'title': 'Blocked request returns success and an answer',
               'hypothesis': 'a rejected request receives a usable response',
               'trigger': 'blocked input', 'impact': 'caller may treat denial as success',
               'input_path': 'name', 'references': [ctx.reference('dns.go', 4, 4)],
               'questions': ['Does the caller honor Code?']}
        def ask(prompt, payload):
            data = json.loads(payload)
            if prompt == ed.DISCOVER:
                candidates = [raw] if data['source']['start_line'] <= 4 <= data['source']['end_line'] else []
                return {'action': 'finish', 'unit_id': data['unit_id'], 'candidates': candidates}, None
            return {'action': 'finish', 'candidate_id': data['candidate_id'], 'status': 'unknown',
                    'reason': 'caller behavior needs review', 'unresolved': ['caller behavior'],
                    'claims': []}, None
        result = ed.run(self.root, self.index(), {}, [], {}, ask)
        self.assertEqual(len(result['findings']), 1)
        item = result['triage_queue'][0]
        self.assertEqual(item['triage_state'], 'needs_review')
        self.assertEqual(item['location'], {'file': 'dns.go', 'line': 4})
        self.assertEqual(item['source_reference']['snippet'],
                         ' return &Response{Code: 0, Answers: []string{name}}')
        self.assertEqual(item['questions'], ['caller behavior'])
        self.assertIn('block, reject, or deny path', ed.DISCOVER)
        self.assertIn('externally controlled object metadata', ed.DISCOVER)

    def test_discovery_failure_is_not_clean_scan(self):
        ctx, _, candidate = self.sample()
        out = ed.run(self.root, self.index(), {}, [candidate], {}, lambda *a: (None, 'timeout'))
        self.assertEqual(out['status'], 'partial')
        self.assertEqual(len(out['findings']), 1)
        self.assertTrue(all(t['status'] == 'failed' for t in out['tasks']))

    def test_range_check_kept_as_hypothesis_in_enhanced(self):
        key = 'a.go:F'
        extraction = {'semantic_inputs': [{'type': 'network', 'line': 2, 'desc': 'input'}],
                      'semantic_sinks': [], 'observed_checks': []}
        flow = {'sources': [{'type': 'http_request', 'line': 2, 'pattern': 'input'}], 'sinks': [], 'sanitizers': []}
        sizes = {key: {'range_checks': [{'line': 3, 'var': 'n'}],
                       'size_sinks': [{'line': 4, 'var': 'n', 'type': 'alloc_size', 'pattern': 'make'}]}}
        args = ({key: extraction}, {key: flow}, [], {})
        old = decide.build_findings(*args, rules=('R1',), size_flows_by_func=sizes)
        new = decide.build_findings(*args, rules=('R1',), size_flows_by_func=sizes, retain_protection=True)
        self.assertEqual(old, [])
        self.assertTrue(new)

    def test_x4_survives_missing_extraction(self):
        fact = dict(category='access_control', aligned_ratio=1.0, template='t', pattern='p',
                    source={'line': 2, 'type': 'entry'}, sink={'line': 3, 'type': 'resource'})
        args = ({}, {}, [], {})
        self.assertFalse(decide.build_findings(*args, rules=('X4',), x4_facts_by_func={'a.go:F': [fact]}))
        self.assertTrue(decide.build_findings(*args, rules=('X4',), x4_facts_by_func={'a.go:F': [fact]}, retain_protection=True))

    def test_distinct_sinks_survive_enhanced_r2(self):
        facts = [{'source': {'line': 1}, 'sink': {'line': i, 'type': 'sql_query'}} for i in (3, 5)]
        self.assertEqual(len(decide.r2_candidates(facts, [], retain_all=True)), 2)
        self.assertEqual(len(decide.r2_candidates(facts, [])), 1)

    def test_cross_package_context_and_guard_shapes(self):
        self.write('go.mod', 'module example\n\ngo 1.20\n')
        self.write('main.go', 'package p\nimport "example/check"\nfunc Entry(x string) { if check.Allow(x) { use(x) } }\n')
        self.write('check/check.go', 'package check\nfunc Allow(x string) bool { return x != "" }\n')
        import detect_vulns as dv
        from functools import partial
        analyzer = partial(go_ast_analysis.analyze_go_source, binary=self.binary, retain_protection=True)
        ast = dv.stage_ast_scan(str(self.root), max_depth=None, analyzer=analyzer)
        ctx = ed.Context(self.root, self.index(), ast)
        fid = next(k for k, f in ctx.functions.items() if f['name'] == 'Allow')
        result = ctx.tool({'tool': 'get_callers', 'function_id': fid})
        self.assertTrue(result['matches'])
        edge = next(x for x in result['matches'] if x['caller'] == 'main.go:Entry'
                    and x['site']['name'] == 'Allow')
        self.assertEqual(edge['site_reference']['snippet'],
                         'func Entry(x string) { if check.Allow(x) { use(x) } }')
        self.assertEqual(edge['site']['args'][0]['roots'], ['param:0'])
        self.assertEqual(edge['caller_parameters'][0]['name'], 'x')
        target = next(x for x in edge['target_flows'] if x['function'] == 'check/check.go:Allow')
        self.assertEqual(target['parameters'][0]['name'], 'x')
        self.assertEqual(target['return_roots'], ['param:0'])
        self.assertFalse(edge['ambiguous'])
        entry_id = next(k for k, f in ctx.functions.items() if f['name'] == 'Entry')
        outgoing = ctx.tool({'tool': 'get_callees', 'function_id': entry_id})
        self.assertTrue(any(e['site_reference']['start_line'] == 3 and e['target_flows']
                            for e in outgoing['matches']))
        self.assertIn('return x != ""', ctx.tool({'tool': 'read_function', 'function_id': fid})['snippet'])

    def test_ambiguous_call_context_is_not_a_unique_value_path(self):
        self.write('a.go', 'package p\nfunc A(x string) { other(x) }\nfunc B(x string) string { return x }\n')
        ctx = self.ctx()
        keys = ['a.go:A', 'a.go:B']
        ctx.flows = {'a.go:A': {'params': [{'index': 0, 'name': 'x'}],
                              'call_sites': [{'line': 2, 'name': 'other', 'args': [
                                  {'index': 0, 'roots': ['param:0']}]}]},
                     'a.go:B': {'params': [{'index': 0, 'name': 'x'}],
                              'return_roots': ['param:0']}}
        ctx.call_index.resolve = lambda *a, **kw: (keys, 'name_dispatch')
        fid = next(k for k, f in ctx.functions.items() if f['name'] == 'A')
        edge = ctx.tool({'tool': 'get_callees', 'function_id': fid})['matches'][0]
        self.assertTrue(edge['ambiguous'])
        self.assertEqual(edge['resolution'], 'name_dispatch')
        self.assertEqual({x['function'] for x in edge['target_flows']}, set(keys))

    def test_field_use_query_exposes_protocol_producer_and_consumer(self):
        self.write('go.mod', 'module example\n\ngo 1.23\n')
        self.write('protocol/message.go', 'package protocol\ntype Message struct { Path string }\ntype Other struct { Path string }\n')
        self.write('server/send.go', '''package server
import ("net/http"; "example/protocol")
func Produce(r *http.Request) protocol.Message {
 path := r.URL.Path
 if path == "" { path = "/" }
 return protocol.Message{Path: path}
}
func Unrelated() protocol.Other { return protocol.Other{Path: "other"} }
func ShadowPath(r *http.Request) protocol.Message {
 path := r.URL.Path
 { path := "/"; _ = protocol.Message{Path: path} }
 return protocol.Message{Path: path}
}
''')
        self.write('client/receive.go', '''package client
import "example/protocol"
func Consume(m protocol.Message) string { return m.Path }
func Rewrite(m *protocol.Message, path string) { m.Path = path }
func Shadow(m protocol.Message) string {
 before := m.Path
 { m := protocol.Other{}; _ = m.Path }
 return before + m.Path
}
''')
        ctx = self.ctx()
        result = ctx.tool({'tool': 'find_field_uses', 'field': 'Path'})
        matches = result['matches']
        self.assertTrue(any(x['kind'] == 'literal_field' and
                            x['reference']['snippet'] == ' return protocol.Message{Path: path}'
                            for x in matches))
        self.assertTrue(any(x['kind'] == 'selector_read' and x['expression'] == 'm.Path'
                            and x['reference']['file'] == 'client/receive.go' for x in matches))
        self.assertTrue(any(x['kind'] == 'selector_write' and x['expression'] == 'm.Path'
                            and x['reference']['start_line'] == 4 for x in matches))
        self.assertTrue(result['warning'].startswith('Approximate field-name'))
        scoped = ctx.tool({'tool': 'find_field_uses', 'field': 'Path',
                           'path_prefix': 'server/'})
        self.assertTrue(scoped['matches'])
        self.assertTrue(all(x['reference']['file'].startswith('server/')
                            for x in scoped['matches']))
        typed = ctx.tool({'tool': 'find_field_uses', 'field': 'Path',
                          'type_id': 'example/protocol.Message'})
        self.assertTrue(typed['matches'])
        self.assertTrue(all(x['type_id'] == 'example/protocol.Message'
                            for x in typed['matches']))
        self.assertTrue(any(x['kind'] == 'literal_field' and
                            any(src['expression'] == 'r.URL.Path' for src in x['value_sources'])
                            for x in typed['matches']))
        self.assertTrue(any(x['kind'] == 'selector_read' and
                            x['reference']['file'] == 'client/receive.go'
                            for x in typed['matches']))
        self.assertTrue(any(x['type_id'] == 'example/protocol.Other' for x in matches))
        self.assertFalse(any(x['type_id'] == 'example/protocol.Other'
                             for x in typed['matches']))
        shadow = [x for x in matches if x['reference']['file'] == 'client/receive.go'
                  and x['expression'] == 'm.Path' and x['reference']['start_line'] in (6, 7, 8)]
        self.assertEqual([(x['reference']['start_line'], x['type_id']) for x in shadow],
                         [(6, 'example/protocol.Message'),
                          (7, 'example/protocol.Other'),
                          (8, 'example/protocol.Message')])
        shadow_values = [x for x in matches if x['kind'] == 'literal_field'
                         and x['reference']['file'] == 'server/send.go'
                         and x['reference']['start_line'] in (11, 12)]
        self.assertEqual([[src['expression'] for src in x['value_sources']]
                          for x in shadow_values], [['"/"'], ['r.URL.Path']])

    def test_sanitizer_roots_retained_only_in_enhanced_ast(self):
        self.write('main.go', '''package p
import ("html"; "net/http"; "os/exec")
func H(w http.ResponseWriter, r *http.Request) {
 s := html.EscapeString(r.URL.Query().Get("cmd"))
 exec.Command("sh", "-c", s).Run()
}
''')
        old = go_ast_analysis.analyze_go_source(str(self.root), binary=self.binary)
        new = go_ast_analysis.analyze_go_source(str(self.root), binary=self.binary, retain_protection=True)
        def roots(result):
            return [s for f in result['param_flows'] for s in f.get('taint_sinks', []) if s['type'] == 'command_execution']
        self.assertTrue(any(s.get('roots') for s in roots(new)))
        self.assertFalse(any(s.get('roots') for s in roots(old)))

    def test_cli_enhanced_and_test_generator_ids(self):
        import detect_vulns as dv
        import gen_testcases as gt
        self.write('a.go', 'package p\nfunc Hidden(x string){ opaque(x) }\n')
        report = self.root / 'result.json'
        def model(cfg, system, content, **kw):
            if system == dv.load_prompt('detect_domain.md'):
                return {'active_domains': [{'domain': 'NetworkRequestAndProtocolHandling',
                                            'confidence': 1.0, 'evidence': 'offline fixture'}]}, None
            if system == ed.DISCOVER:
                p = json.loads(content)
                return {'action': 'finish', 'unit_id': p['unit_id'], 'candidates': []}, None
            if system == ed.VERIFY:
                p = json.loads(content)
                return {'action': 'finish', 'candidate_id': p['candidate_id'], 'status': 'unknown',
                        'reason': 'unresolved', 'claims': [], 'unresolved': ['precondition']}, None
            return [], None
        argv = ['detect_vulns.py', '--target', str(self.root), '--output', str(report),
                '--rules', 'v2', '--detection-mode', 'enhanced']
        with patch.object(sys, 'argv', argv), patch.object(dv, 'load_env', return_value={
                'LLM_API_KEY': 'stub', 'LLM_BASE_URL': 'http://unused', 'LLM_MODEL': 'stub'}), \
                patch.object(dv, 'call_llm', side_effect=model):
            dv.main()
        dv._ENHANCED_CONTEXT = None
        result = json.loads(report.read_text())
        self.assertEqual(result['schema_version'], 'goforret.enhanced/v1')
        self.assertEqual(result['enhanced']['status'], 'complete')
        self.assertTrue(result['enhanced']['tasks'])
        self.assertEqual(result['enhanced']['limits']['discovery_calls_used'],
                         result['enhanced']['limits']['model_calls_used'])
        self.assertEqual(result['enhanced']['limits']['verification_calls_used'], 0)
        self.assertEqual(result['summary']['detected_candidates'], 0)
        self.assertEqual(result['summary']['needs_review'], 0)
        self.assertEqual(result['enhanced']['triage_queue'], [])
        self.assertEqual(result['scan_info']['confidence']['dimensions'],
                         ['code_evidence', 'ast_corroboration', 'template_support'])
        self.assertGreater(result['scan_info']['total_templates_matched'], 0)
        self.assertNotIn('no_kb', result['scan_info']['filters'])
        fid = 'fixed-id'
        self.assertEqual(gt.make_finding_id({'finding_id': fid}), fid)
        saved = gt.save_outputs(str(self.root), 'tests', fid,
            {'unit_test': {'source': 'package p'}, 'poc': {'source': 'package main'}},
            {'function': 'a.go:Hidden', 'pattern_name': 'same'})
        self.assertTrue(any(fid in f for f in saved['files']))

    def test_no_kb_cli_option_is_removed(self):
        script = Path(__file__).resolve().parents[1] / 'detect_vulns.py'
        result = subprocess.run([sys.executable, str(script), '--target', str(self.root), '--no-kb'],
                                text=True, capture_output=True)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('unrecognized arguments: --no-kb', result.stderr)

    def test_cli_enhanced_call_cap_is_reported_as_partial(self):
        import detect_vulns as dv
        self.write('a.go', 'package p\nfunc Hidden(x string){ opaque(x) }\n')
        report = self.root / 'capped.json'
        discovery_calls = []
        def model(cfg, system, content, **kw):
            if system == dv.load_prompt('detect_domain.md'):
                return {'active_domains': []}, None
            if system == ed.DISCOVER:
                discovery_calls.append(content)
                p = json.loads(content)
                return {'action': 'finish', 'unit_id': p['unit_id'], 'candidates': []}, None
            return [], None
        argv = ['detect_vulns.py', '--target', str(self.root), '--output', str(report),
                '--rules', 'v2', '--detection-mode', 'enhanced',
                '--enhanced-max-model-calls', '1']
        with patch.object(sys, 'argv', argv), patch.object(dv, 'load_env', return_value={
                'LLM_API_KEY': 'stub', 'LLM_BASE_URL': 'http://unused', 'LLM_MODEL': 'stub'}), \
                patch.object(dv, 'call_llm', side_effect=model):
            dv.main()
        dv._ENHANCED_CONTEXT = None
        result = json.loads(report.read_text())['enhanced']
        self.assertEqual(len(discovery_calls), 1)
        self.assertEqual(result['status'], 'partial')
        self.assertEqual(result['limits']['max_model_calls'], 1)
        self.assertEqual(result['limits']['model_calls_used'], 1)
        self.assertTrue(any(t['status'] == 'pending' for t in result['tasks']))

    def test_guard_pairs_survive_until_independent_verification(self):
        import detect_vulns as dv
        for body, expected in [('println(n)', 'supported'), ('return', 'refuted')]:
            with self.subTest(body=body):
                self.write('main.go', '''package p
import ("net/http"; "strconv")
func H(w http.ResponseWriter, r *http.Request) {
 n, _ := strconv.Atoi(r.URL.Query().Get("n"))
 if n < 0 || n > 100 { ''' + body + ''' }
 _ = make([]byte,n)
}
''')
                report = self.root / 'guard.json'
                def model(cfg, prompt, payload, **kw):
                    if prompt == dv.load_prompt('detect_domain.md'):
                        return {'active_domains': []}, None
                    if prompt == ed.DISCOVER:
                        p = json.loads(payload)
                        return {'action': 'finish', 'unit_id': p['unit_id'], 'candidates': []}, None
                    if prompt == ed.VERIFY:
                        p = json.loads(payload)
                        lines = (self.root / 'main.go').read_text().splitlines()
                        def claim(kind, n):
                            return {'kind': kind, 'statement': 'offline fixture assertion', 'references': [
                                {'file': 'main.go', 'start_line': n, 'end_line': n, 'snippet': lines[n-1]}]}
                        claims = [claim('operation',6), claim('protection',5)] if expected == 'refuted' else [
                            claim('input',4), claim('operation',6), claim('impact',6)]
                        return {'action': 'finish', 'candidate_id': p['candidate_id'], 'status': expected,
                                'reason': 'offline fixture verdict', 'claims': claims, 'unresolved': []}, None
                    ids = json.loads(payload.split('Function IDs (same input order): ')[1])
                    return [dict(function_id=k, purpose='allocate', semantic_inputs=[], semantic_sinks=[], observed_checks=[]) for k in ids], None
                argv = ['detect_vulns.py','--target',str(self.root),'--output',str(report),
                        '--rules','v2,R1','--detection-mode','enhanced']
                with patch.object(sys,'argv',argv), patch.object(dv,'load_env',return_value={
                        'LLM_API_KEY':'stub','LLM_BASE_URL':'http://unused','LLM_MODEL':'stub'}), \
                        patch.object(dv,'call_llm',side_effect=model):
                    dv.main()
                dv._ENHANCED_CONTEXT = None
                result = json.loads(report.read_text())
                candidates = [c for c in result['enhanced']['candidates'] if c['rule_id']=='R1']
                self.assertTrue(candidates)
                self.assertTrue(all(c['protection_hypotheses'] for c in candidates))
                self.assertTrue(all(c['validation_status']==expected for c in candidates))
                if expected=='refuted':
                    self.assertFalse(any(c['rule_id']=='R1' for c in result['findings']))

    def test_unknown_and_invalid_verdict_shapes_do_not_drop_candidate(self):
        ctx, raw, c = self.sample()
        bad = {'action':'finish','candidate_id':c['finding_id'],'status':'supported','reason':'bad',
               'unresolved':[], 'claims':[{'kind':[], 'statement':'bad','references':raw['references']}]}
        self.assertEqual(ed.verify(ctx,lambda *a:(bad,None),c,lambda:False)['validation_status'],'unknown')
        out = ed.run(self.root,self.index(),{},[],{},lambda *a:({'action':'finish','unit_id':'wrong','candidates':[]},None))
        self.assertEqual(out['status'],'partial')

    def test_generated_test_paths_match_metadata_ids_and_do_not_collide(self):
        import gen_testcases as gt
        for fid in ('one', 'two'):
            saved = gt.save_outputs(str(self.root),'out',fid,{'unit_test':{'source':'package p'},
                    'poc':{'source':'package main'}},{'function':'a.go:F','pattern_name':'same'})
            self.assertIn('unit/'+fid+'_test.go',saved['files'])
        entries = json.loads((self.root/'out/metadata.json').read_text())['entries']
        self.assertEqual(set(entries),{'one','two'})

    def test_strong_validator_is_a_hypothesis_not_automatic_refutation(self):
        import validator_contract as vc
        import param_taint
        target = Path(__file__).resolve().parent / 'fixtures' / 'r3'
        ast = go_ast_analysis.analyze_go_source(str(target), binary=self.binary, retain_protection=True)
        mods = param_taint.load_modules(str(target))
        old = vc.r3_facts(ast['param_flows'], mods, infer_purpose=True)
        new = vc.r3_facts(ast['param_flows'], mods, infer_purpose=True, retain_protection=True)
        self.assertNotIn('redirect.go:validateStrictRedirect', old)
        self.assertIn('redirect.go:validateStrictRedirect', new)
        self.assertIn('url.go:validateStrictURL', new)

    def test_malformed_tool_request_and_claim_references_are_unknown(self):
        ctx, raw, c = self.sample()
        for response in [
            {'action':'query','requests':['not an object']},
            {'action':'finish','candidate_id':c['finding_id'],'status':'supported','reason':'x','unresolved':[],
             'claims':[{'kind':'operation','statement':'x','references':42}]},
        ]:
            result = ed.verify(ctx,lambda *a:(response,None),c,lambda:False)
            self.assertEqual(result['validation_status'],'unknown')

    def test_enhanced_testcase_reads_method_from_ast_and_accepts_reference_list(self):
        import gen_testcases as gt
        self.write('a.go', 'package p\ntype Handler struct{}\nfunc (h *Handler) M(x string) {\n println("}")\n}\n')
        ctx = self.ctx()
        fid = next(k for k, f in ctx.functions.items() if f['name'] == 'Handler.M')
        gt._ENHANCED_TEST_CONTEXT = ctx
        try:
            source = gt.extract_function_source(str(self.root), 'a.go', 'Handler.M', fid)
            self.assertIn('println("}")', source)
            self.assertIn('M(x string)', source)
            finding = {'function':'a.go:Handler.M','finding_id':'id',
                       'missing_step_category':'other_security',
                       'evidence':[ctx.reference('a.go',4,4)],'reasoning':'possible issue'}
            user_msg = gt.build_user_message(finding, source, *gt.get_template('other_security'),
                {'module_path':'p','go_version':'1.23'}, 'p')
            self.assertIn('a.go', user_msg)
            self.assertIn('case-specific', user_msg)
        finally:
            gt._ENHANCED_TEST_CONTEXT = None

    def test_testcase_cli_filters_unknown_and_rejects_source_drift(self):
        import gen_testcases as gt
        ctx, raw, candidate = self.sample()
        candidate.update(validation_status='supported', source_support=True)
        unknown = dict(candidate, finding_id='unknown-id', validation_status='unknown')
        report = self.root / 'result.json'
        report.write_text(json.dumps({'schema_version':'goforret.enhanced/v1',
            'enhanced':{'source_hashes':{f:d['hash'] for f,d in ctx.files.items()}},
            'findings':[candidate,unknown]}))
        output = self.root / 'generated'
        argv = ['gen_testcases.py','--target',str(self.root),'--report',str(report),
                '--output-dir',str(output),'--skip-compile','--delay','0']
        def generate(*args, **kwargs):
            self.assertIn('func Hidden', args[3])
            return {'unit_test': {'source':'package p'}}, None
        with patch.object(sys,'argv',argv), patch.object(gt,'load_env',return_value={
                'LLM_API_KEY':'stub','LLM_BASE_URL':'http://unused','LLM_MODEL':'stub'}), \
                patch.object(gt,'generate_one',side_effect=generate):
            gt.main()
        self.assertTrue((output/self.root.name/'unit'/f"{candidate['finding_id']}_test.go").exists())
        self.assertFalse((output/self.root.name/'unit'/'unknown-id_test.go').exists())
        gt._ENHANCED_TEST_CONTEXT = None
        self.write('a.go','package p\nfunc Hidden(x string) {}\n')
        with patch.object(sys,'argv',argv), patch.object(gt,'load_env',return_value={
                'LLM_API_KEY':'stub','LLM_BASE_URL':'http://unused','LLM_MODEL':'stub'}):
            with self.assertRaises(SystemExit):
                gt.main()
        gt._ENHANCED_TEST_CONTEXT = None


if __name__ == '__main__':
    unittest.main()
